"use client"

import type React from "react"

import { useState, useRef, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { ScrollablePanel } from "@/components/ui/scrollable-panel"
import { Send, Sparkles, Loader2, BookOpen } from "lucide-react"
import { ChatHistoryManager } from "@/lib/chat-history"

interface Message {
  id: string
  role: "user" | "assistant"
  content: string
}

interface ChatPanelProps {
  projectId: string
  onCodeUpdate: (code: string, reason?: string) => void
  currentCode: string
  contractName: string
  network: string
}

// Mock codebase context - in a real implementation, this would be dynamically generated
const getCodebaseContext = () => {
  return `Project Structure:
- app/page.tsx: Landing page with project creation
- app/project/[id]/page.tsx: Main IDE interface
- components/chat-panel.tsx: AI chat interface
- components/code-editor.tsx: Code editor component
- components/console-panel.tsx: Console/output panel
- lib/stacks-wallet.ts: Stacks blockchain integration
- lib/clarity-validator.ts: Clarity code validation
- lib/project-storage.ts: Project persistence
- lib/chat-history.ts: Chat history management

Key Technologies:
- Next.js 15 with React Server Components
- TypeScript for type safety
- Tailwind CSS for styling
- Radix UI for accessible components
- Stacks blockchain for smart contract deployment
- Groq Llama 3.3 70b for AI assistance

Core Features:
- AI-powered Clarity code generation
- Real-time syntax validation
- Private key-based deployment
- Project management and persistence
- Chat history with code versioning`
}

export function ChatPanel({ projectId, onCodeUpdate, currentCode, contractName, network }: ChatPanelProps) {
  const scrollAreaRef = useRef<HTMLDivElement>(null)
  const [messages, setMessages] = useState<Message[]>(() => {
    // Load chat history from localStorage
    const history = ChatHistoryManager.getHistory(projectId)
    if (history.messages.length > 0) {
      return history.messages
    }
    
    // Comprehensive welcome message with useful commands
    return [
      {
        id: "welcome",
        role: "assistant",
        content: `Hello! I'm Clarity AI, your smart contract assistant.\n\nI can help you build secure Stacks blockchain smart contracts. Just describe what you want to build, and I'll generate the code for you.\n\nExamples:\n- "Create an NFT contract"\n- "Add staking functionality"\n- "Create a token contract"\n\nYou can also ask me to explain any part of the codebase.`,
      },
    ]
  })
  const [input, setInput] = useState("")
  const [isLoading, setIsLoading] = useState(false)
  const [lastProcessedMessage, setLastProcessedMessage] = useState<string>("")

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    if (scrollAreaRef.current) {
      const viewport = scrollAreaRef.current.querySelector('[data-slot="scroll-area-viewport"]') as HTMLDivElement
      if (viewport) {
        // Use requestAnimationFrame for better performance
        requestAnimationFrame(() => {
          viewport.scrollTop = viewport.scrollHeight
        })
      }
    }
  }, [messages, isLoading])

  // Extract only text explanations from AI responses (no code in chat)
  useEffect(() => {
    const lastMessage = messages[messages.length - 1]
    if (lastMessage && lastMessage.role === "assistant" && lastMessage.content !== lastProcessedMessage && lastMessage.id !== "welcome") {
      setLastProcessedMessage(lastMessage.content)

      const content = lastMessage.content

      // Check if response contains Clarity code
      const hasDefine = content.includes("define-")
      const hasBegin = content.includes("(begin")
      const hasLet = content.includes("(let")
      const hasMap = content.includes("(define-map")
      const hasDataVar = content.includes("(define-data-var")
      const hasFt = content.includes("(define-fungible-token")
      const hasNft = content.includes("(define-non-fungible-token")

      // Enhanced detection for Clarity code patterns
      const isLikelyClarityCode = hasDefine || hasBegin || hasLet || hasMap || hasDataVar || hasFt || hasNft || 
                                content.includes("(define-constant") || content.includes("(define-trait") ||
                                content.includes("(impl-trait") || content.includes("(use-trait")

      if (isLikelyClarityCode) {
        // Try to extract code from markdown blocks first
        const codeBlockMatch = content.match(/```(?:clarity)?\n([\s\S]*?)```/)

        if (codeBlockMatch) {
          // Code is in markdown block
          const code = codeBlockMatch[1].trim()
          // Extract only the explanation (text outside code blocks)
          const explanation = content.replace(/```(?:clarity)?\n[\s\S]*?```/, "").trim()
          
          // Send code to editor
          onCodeUpdate(code, explanation || "Code generated by Clarity AI")
          
          // Save code version to history
          ChatHistoryManager.saveCodeVersion(projectId, code, explanation || "Code generated by Clarity AI")
          
          // Update chat to show only explanation (without code)
          if (explanation) {
            setMessages(prev => {
              const newMessages = [...prev]
              const lastMsg = newMessages[newMessages.length - 1]
              if (lastMsg.id === lastMessage.id) {
                lastMsg.content = explanation
              }
              return newMessages
            })
          } else {
            // If no explanation, show a generic message
            setMessages(prev => {
              const newMessages = [...prev]
              const lastMsg = newMessages[newMessages.length - 1]
              if (lastMsg.id === lastMessage.id) {
                lastMsg.content = "I've generated the code for your request. You can view it in the editor."
              }
              return newMessages
            })
          }
        } else if (!content.includes("```")) {
          // Response is pure code (no markdown)
          onCodeUpdate(content, "Code generated by Clarity AI")
          
          // Save code version to history
          ChatHistoryManager.saveCodeVersion(projectId, content, "Code generated by Clarity AI")
          
          // Update chat to show a generic message instead of code
          setMessages(prev => {
            const newMessages = [...prev]
            const lastMsg = newMessages[newMessages.length - 1]
            if (lastMsg.id === lastMessage.id) {
              lastMsg.content = "I've generated the code for your request. You can view it in the editor."
            }
            return newMessages
          })
        }
      }
    }
  }, [messages, lastProcessedMessage, onCodeUpdate, projectId])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!input.trim() || isLoading) return

    // Add user message
    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: input,
    }

    setMessages((prev) => [...prev, userMessage])
    // Save to chat history
    ChatHistoryManager.saveMessage(projectId, userMessage)
    setInput("")
    setIsLoading(true)

    try {
      // Add temporary assistant message
      const assistantMessageId = `assistant-${Date.now()}`
      const assistantMessage: Message = {
        id: assistantMessageId,
        role: "assistant",
        content: "",
      }
      setMessages((prev) => [...prev, assistantMessage])
      // Save to chat history
      ChatHistoryManager.saveMessage(projectId, assistantMessage)

      // Get codebase context
      const codebaseContext = getCodebaseContext()

      // Call the API
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          messages: [...messages, userMessage],
          contractName,
          network,
          currentCode,
          codebaseContext,
        }),
      })

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }

      if (!response.body) {
        throw new Error("Response body is null")
      }

      // Process the stream
      const reader = response.body.getReader()
      const decoder = new TextDecoder()
      let done = false
      let assistantContent = ""

      while (!done) {
        const { value, done: readerDone } = await reader.read()
        done = readerDone

        if (value) {
          const chunk = decoder.decode(value, { stream: true })
          assistantContent += chunk

          // Update the assistant message
          setMessages((prev) => {
            const newMessages = [...prev]
            const lastMessage = newMessages[newMessages.length - 1]
            if (lastMessage.id === assistantMessageId) {
              lastMessage.content = assistantContent
              // Update chat history
              ChatHistoryManager.saveMessage(projectId, lastMessage)
            }
            return newMessages
          })

          // Scroll to bottom as new content arrives
          if (scrollAreaRef.current) {
            const viewport = scrollAreaRef.current.querySelector('[data-slot="scroll-area-viewport"]') as HTMLDivElement
            if (viewport) {
              requestAnimationFrame(() => {
                viewport.scrollTop = viewport.scrollHeight
              })
            }
          }
        }
      }
    } catch (error) {
      console.error("Error:", error)
      setMessages((prev) => [
        ...prev,
        {
          id: `error-${Date.now()}`,
          role: "assistant",
          content: "Sorry, I encountered an error. Please try again.",
        },
      ])
    } finally {
      setIsLoading(false)
      // Final scroll to bottom
      setTimeout(() => {
        if (scrollAreaRef.current) {
          const viewport = scrollAreaRef.current.querySelector('[data-slot="scroll-area-viewport"]') as HTMLDivElement
          if (viewport) {
            viewport.scrollTop = viewport.scrollHeight
          }
        }
      }, 100)
    }
  }

  return (
    <div className="flex flex-col h-full bg-black chat-panel-container">
      {/* Header */}
      <div className="p-4 border-b border-white/10 flex-shrink-0 bg-black">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-white" />
          <h2 className="font-semibold text-sm text-white">Clarity AI</h2>
        </div>
      </div>

      {/* Messages */}
      <ScrollablePanel className="flex-1 p-4 chat-messages-container" ref={scrollAreaRef}>
        <div className="space-y-4 pr-2">
          {messages.map((message) => (
            <div 
              key={message.id} 
              className={`flex chat-message ${message.role === "user" ? "user" : "assistant"}`}
            >
              <div 
                className={`chat-message-content rounded-lg p-3 max-w-[90%] ${
                  message.role === "user" 
                    ? "bg-white text-black ml-auto" 
                    : message.id === "welcome"
                      ? "bg-white/10 text-white border border-white/10"
                      : "bg-white/5 text-white"
                }`}
              >
                <p className="whitespace-pre-wrap break-words">{message.content}</p>
              </div>
            </div>
          ))}
          {isLoading && (
            <div className="flex justify-start chat-message assistant">
              <div className="chat-message-content bg-white/5 text-white rounded-lg p-3">
                <div className="flex items-center gap-2">
                  <Loader2 className="w-3 h-3 animate-spin" />
                  <span className="text-xs text-gray-400">Clarity AI is thinking...</span>
                </div>
              </div>
            </div>
          )}
        </div>
      </ScrollablePanel>

      {/* Input - Fixed at bottom */}
      <div className="p-4 border-t border-white/10 chat-input-container flex-shrink-0 bg-black">
        <form onSubmit={handleSubmit} className="flex gap-2 chat-input-form">
          <Textarea
            placeholder="Describe what you want to build... (e.g., 'Create an NFT contract')"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault()
                handleSubmit(e as any)
              }
            }}
            className="min-h-[60px] resize-none chat-input-textarea bg-black border-white/20 text-white placeholder:text-gray-500"
            disabled={isLoading}
          />
          <Button type="submit" size="icon" disabled={!input.trim() || isLoading} className="self-end chat-send-button h-[60px] rounded-full bg-white text-black hover:bg-gray-200">
            {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
          </Button>
        </form>
        <div className="flex items-center gap-4 mt-2 text-xs text-gray-500">
          <span>Press Enter to send, Shift+Enter for new line</span>
          <div className="flex items-center gap-1">
            <BookOpen className="w-3 h-3" />
            <span>Ask about codebase</span>
          </div>
        </div>
      </div>
    </div>
  )
}